### ISSUE TITLE
Failed to load Duck.gltf model

### ISSUE THREAD

**Issue by cx20** [playcanvas/playcanvas-gltf#1]
I tried loading Duck.gltf using PlayCanvas + glTF Loader.
http://jsdo.it/cx20/yh4S

However, glTF-Embedded format can be load, but otherwise it got an error.

[OK] https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Duck/glTF-Embedded/Duck.gltf
[NG] https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Duck/glTF/Duck.gltf

```
gltf-loader.js:5 
Uncaught DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at dataURItoArrayBuffer (https://cdn.rawgit.com/playcanvas/playcanvas-gltf/5489ff62/src/gltf-loader.js:5:26)
    at https://cdn.rawgit.com/playcanvas/playcanvas-gltf/5489ff62/src/gltf-loader.js:516:35
    at Array.forEach (<anonymous>)
    at loadBuffers (https://cdn.rawgit.com/playcanvas/playcanvas-gltf/5489ff62/src/gltf-loader.js:515:26)
    at loadGltf (https://cdn.rawgit.com/playcanvas/playcanvas-gltf/5489ff62/src/gltf-loader.js:602:54)
    at XMLHttpRequest.req.onload (http://jsrun.it/cx20/yh4S:132:16)
```

https://github.com/playcanvas/playcanvas-gltf/blob/master/src/gltf-loader.js#L5

If the normal glTF format is supported, I will add playcanvas-gltf to [gltf-test](https://github.com/cx20/gltf-test).

**Comment by willeastcott** [comment]
This is because the glTF loader currently only supports:

- Embedded glTF
- Binary glTF (.glb)

I just committed the first part of support non-embedded glTF files here: https://github.com/playcanvas/playcanvas-gltf/commit/6ff7720d12a1a54b2b758f710e626a5a7bdf80db

This gives the loader code access to the external .bin and image files referenced by the glTF file. Now I just need to update the loader to load the days from these files.

**Comment by cx20** [comment]
I have understood the status of current glTF Loader.
I added the following tests to gltf-test. Other tests are added when normal glTF format is supported.

- Format Tests ( https://github.com/cx20/gltf-test#format-tests )
- All Tests ( https://cx20.github.io/gltf-test/ )

https://github.com/cx20/gltf-test#format-tests
![image](https://user-images.githubusercontent.com/1833979/34910572-77fc634a-f8fb-11e7-92c8-a93fae6a42f7.png)

https://cx20.github.io/gltf-test/
![image](https://user-images.githubusercontent.com/1833979/34910678-952c3dd0-f8fd-11e7-97ac-a6f2087c019b.png)

**Comment by cx20** [comment]
I tried loading non-embedded glTF files with the latest glTF viewer.
Since the geometry of Duck is displayed, it seems that the bin file can be load correctly.
However, image file seems not to be load.
![image](https://user-images.githubusercontent.com/1833979/35190648-a8bfc19e-fea9-11e7-8f96-4f9c6d2875c9.png)

**Comment by willeastcott** [comment]
Fixed in https://github.com/playcanvas/playcanvas-gltf/commit/5b04dc1fa633c25e6a1e5067b85fa50ad01b7342

**Comment by cx20** [comment]
I confirmed that non-embedded glTF files can be load with the latest glTF viewer.
![image](https://user-images.githubusercontent.com/1833979/35197070-fbb360da-ff1d-11e7-8e85-33d183189a01.png)

**Comment by willeastcott** [comment]
Excellent. 👍

**Comment by cx20** [comment]
However, in my [gltf-test](https://cx20.github.io/gltf-test/), I can not display it yet.
https://cx20.github.io/gltf-test/examples/playcanvas/index.html?model=Duck&scale=1&type=glTF

I think it is necessary to pass more than one file name, but I did not understand how to do it.

**Comment by willeastcott** [comment]
Currently, you have to pass an array of File objects, which is not so easy to generate. At the moment, this is generated in the viewer index.html. I think I'm going to change this such that you can pass in a callback to the loadGltf function, and when the loader requests a file, you can load it from whatever source you like.

**Comment by willeastcott** [comment]
OK. I'll figure out an easier mechanism for loading multi-file glTF.

**Comment by willeastcott** [comment]
I have made it much easier to loaded multi-file glTF for you. See [this](https://github.com/playcanvas/playcanvas-gltf/commit/fc6cb24b1743bfb4e45895679dd9696b0a1319b9) change. Now you can do:

            app.assets.loadFromUrl('assets/car.gltf', 'json', function (err, asset) {
                var json = asset.resource;
                var gltf = JSON.parse(json);
                loadGltf(gltf, app.graphicsDevice, function (roots) {
                    // add the loaded scene to the hierarchy
                    roots.forEach(function (root) {
                        app.root.addChild(root);
                    });
                }, {
                    basePath: 'assets/'
                });
            });

**Comment by cx20** [comment]
I confirmed that playcanvas-gltf supported normal glTF format and added test to [gltf-test](https://github.com/cx20/gltf-test).
The following is the current test result.

https://github.com/cx20/gltf-test#format-tests
![image](https://user-images.githubusercontent.com/1833979/35479721-4e94052a-0441-11e8-9f07-7b0f08df6c10.png)

https://github.com/cx20/gltf-test#simple-models-for-testing-individual-features
![image](https://user-images.githubusercontent.com/1833979/35479768-780d36d2-0442-11e8-8ea0-e7f0ca232b88.png)

https://github.com/cx20/gltf-test#more-complex-models
![image](https://user-images.githubusercontent.com/1833979/35479794-2c798bca-0443-11e8-8fd4-17c83ac1c833.png)

https://github.com/cx20/gltf-test#pbr-models
![image](https://user-images.githubusercontent.com/1833979/35479815-a8f08028-0443-11e8-86e8-3a16dab433f4.png)

https://github.com/cx20/gltf-test#further-pbr-models
![image](https://user-images.githubusercontent.com/1833979/35479837-05429668-0444-11e8-9db1-c2abb01af655.png)

https://github.com/cx20/gltf-test#agi-sample-models
![image](https://user-images.githubusercontent.com/1833979/35479850-942abdba-0444-11e8-8ab2-77cce176f8ef.png)

**Comment by willeastcott** [comment]
OK, well, I guess that's progress. 😄 

TODO:

* Keyframe animation
* Skinning
* Morphing
* Draco support
* Vertex color support
* Fix tangent space problem

**Comment by willeastcott** [comment]
I've fixed the problem preventing the SciFi Helment loading [here](https://github.com/playcanvas/playcanvas-gltf/commit/d079ea9d99b4b38057c6942a34dbff05660c5a46):

![image](https://user-images.githubusercontent.com/697563/35485763-dd2219f4-0418-11e8-89c8-38203a94e660.png)

**Comment by cx20** [comment]
I confirmed that the Sci Fi Helmet is displayed and I updated the status of gltf-test.
https://github.com/cx20/gltf-test#further-pbr-models

**Comment by willeastcott** [comment]
I've done a first pass at supporting morph target animation from glTF. This means the following models should now work correctly:

* AnimatedMorphCube
* AnimatedMorphSphere
* SimpleMorph

**Comment by cx20** [comment]
I confirmed that morph target animation works and updated the status of gltf-test.
https://github.com/cx20/gltf-test#simple-models-for-testing-individual-features

**Comment by willeastcott** [comment]
I've just added support for vertex colors. This required an update to the PlayCanvas Engine itself. See [here](https://github.com/playcanvas/engine/pull/1080). This allows tests 'VertexColorTest' and 'BoxVertexColors' to work correctly. Because the engine PR to support vertex colors has not yet been merged, I've checked in a 'dev' build of the engine into this repo. Hopefully we can merge and deploy that on Monday.

**Comment by cx20** [comment]
I understand. I will test again when PR is merged into the PlayCanvas Engine.

**Comment by cx20** [comment]
I confirmed that VertexColorTest and BoxVertexColors can be displayed with the latest PlayCanvas engine.

**Comment by willeastcott** [comment]
Excellent. 👍 I'll look at transform-based keyframes next, I think.

**Comment by willeastcott** [comment]
My [latest commit](https://github.com/playcanvas/playcanvas-gltf/commit/d3c25bbc3bb290b402306fadaf82d860a96875e4) fixes:

* Animated Triangle
* Box Animated
* Cesium Milk Truck
* Animated Cube

We're getting closer... 😸

**Comment by cx20** [comment]
I confirmed that the above five models will be displayed.
https://github.com/cx20/gltf-test

**Comment by willeastcott** [comment]
I've added initial support for Draco mesh compression [here](https://github.com/playcanvas/playcanvas-gltf/commit/46c9c22b4d1c7385f8f8d13faa686e23c633e695). Try the duck to verify this for yourself.

**Comment by cx20** [comment]
Thank you for working quickly to support Draco. I confirmed that Box and Duck glTF Draco format can be displayed. https://cx20.github.io/gltf-test/index.html
I am waiting for other models to be displayed as well.

**Comment by willeastcott** [comment]
Ah yes, most other Draco models weren't loading. Corset and Boombox now work too because of [this commit](https://github.com/playcanvas/playcanvas-gltf/commit/2f3e70fe42eec7f2ed824ee634e3bfffba33e567). Still some problems with GearboxAssy. I'll look into it...

**Comment by cx20** [comment]
I noticed a mystery problem. However it is interesting :-)

2CylinderEngine.gltf Draco format result:
![image](https://user-images.githubusercontent.com/1833979/36337360-ec33b596-13d7-11e8-8cf9-5b257a9bd85f.png)

Lantern.gltf Draco format result:
![image](https://user-images.githubusercontent.com/1833979/36337376-35a0b94a-13d8-11e8-8f13-9aacf3bdd5d2.png)

**Comment by willeastcott** [comment]
OK, this is [now fixed](https://github.com/playcanvas/playcanvas-gltf/commit/6203bfb0934d1565ad988a4fe0dfc2020562da2a). All Draco models should now work in PlayCanvas (obviously, I still need to finish skinning support though).

2CylinderEngine.gltf Draco format result:
![image](https://user-images.githubusercontent.com/697563/36342036-fec53de0-13ac-11e8-8981-52d544b6b9c9.png)

Lantern.gltf Draco format result:
![image](https://user-images.githubusercontent.com/697563/36342043-1e000370-13ad-11e8-9104-e9017c738309.png)

**Comment by cx20** [comment]
I confirmed that the glTF Draco model is displayed except skinning animation. I updated the following status.
https://github.com/cx20/gltf-test#format-tests
![image](https://user-images.githubusercontent.com/1833979/36342352-99f41f82-1440-11e8-8171-a715fe3ae468.png)

**Comment by willeastcott** [comment]
I have now [implemented skinning](https://github.com/playcanvas/playcanvas-gltf/commit/f16319bc6efa0c702b933bfb23a3b08b3cec461b). This means all Draco models now work correctly. Plus the following scenes:

* RiggedSimple
* BrainStem

Unfortunately, there are some issues with:

* RiggedFigure
* Monster
* CesiumMan

![image](https://user-images.githubusercontent.com/697563/36364249-d72b4094-14f7-11e8-9f80-ffdc8f28ac1c.png)

**Comment by willeastcott** [comment]
I think I see why RiggedSimple has problems. There are vertices where the skin weights do not sum to 1. Calling @guycalledfrank - what do you think about this? I could try normalizing the weights on load, but I notice Three.js can load this model fine without renormalizing. Three's skinning GLSL is slightly different to PlayCanvas. I wonder if PlayCanvas is bugged somehow...

**Comment by cx20** [comment]
I updated the status of gltf-test because I confirmed that RiggedSimple and BrainStem are displayed correctly.
https://github.com/cx20/gltf-test

**Comment by willeastcott** [comment]
OK, the following now work due to [this PR](https://github.com/playcanvas/engine/pull/1097/files) in the engine:

* RiggedFigure
* Monster
* CesiumMan

So you can now also remove the comment 'skinning animation support yet' for the Draco format.

**Comment by cx20** [comment]
Wonderful work! I confirmed that all skinning animation models are displayed.
https://github.com/cx20/gltf-test

**Comment by willeastcott** [comment]
Since this issue was originally about fixing unpacked glTF scenes, I'm going to close it.

The remaining issues that I'm aware of that are preventing the PlayCanvas glTF loader from passing every one of your test have now been added as new issues. These cover:

* Sparse accessors.
* Interleaved vertex data.
* Tangent generation.

Thank you _so much_ for all your help so far! 😄
