### ISSUE TITLE
SambaDancing.gltf's dance animation is unstable

### ISSUE THREAD

**Issue by cx20** [playcanvas/playcanvas-gltf#10]
I tried to animate SambaDancing.gltf with playcanvas-gltf.
Although it is correctly displayed at first, it seems that animation behavior becomes unstable after a while (if left for several minutes).

[PlayCanvas + SambaDancing.gltf result:](http://jsdo.it/cx20/eDKW)

At first there is no problem
![sambadancing_ok](https://user-images.githubusercontent.com/1833979/37554714-0d9f6b2c-2a20-11e8-980b-26d4246eb23d.gif)

It will become unstable after a while
![sambadancing_ng](https://user-images.githubusercontent.com/1833979/37554716-12222540-2a20-11e8-8629-21a9727bb39f.gif)

**Comment by willeastcott** [comment]
I see why this is happening. The loader assumes that all animation curves on each node have the same duration, but that is not true for this model. And animations are run on each joint independently at the moment and also loop independently. So on every loop, the joints get more and more desynchronized. I'll rework the animation to run on the skeleton globally and loop at a single time for all joints.

**Comment by cx20** [comment]
I confirmed that this problem has been resolved.
http://jsdo.it/cx20/gHSE
