### ISSUE TITLE
Failed to load VoxelCorgi.gltf

### ISSUE THREAD

**Issue by cx20** [playcanvas/playcanvas-gltf#12]
I tried to display VoxelCorgi.gltf ([output by glTF Exporter of Three.js](http://jsdo.it/cx20/CDcF)) on PlayCanvas.
However, it seems to fail to load the model.

PlayCanvas + VoxelCorgi.gltf result:
http://jsdo.it/cx20/MNU4

```javascript
laycanvas-latest.js:16005 
Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.pc.calculateTangents (playcanvas-latest.js:16005)
    at playcanvas-gltf.js:674
    at Array.forEach (<anonymous>)
    at translateMesh (playcanvas-gltf.js:511)
    at playcanvas-gltf.js:1131
    at Array.map (<anonymous>)
    at parse (playcanvas-gltf.js:1130)
    at playcanvas-gltf.js:1257
    at parse (playcanvas-gltf.js:1119)
    at playcanvas-gltf.js:1255
```

Three.js + VoxelCorgi.gltf result:
http://jsdo.it/cx20/ahsW

![image](https://user-images.githubusercontent.com/1833979/37561054-2286cd4c-2a88-11e8-8c40-b7700c67d05e.png)

**Comment by cx20** [comment]
Although the error has been resolved, half of the model appears to be black. Is it another Issue?

|Three.js|PlayCanvas|
|:--------:|:----------:|
|[![image](https://user-images.githubusercontent.com/1833979/37563034-cf461754-2aba-11e8-9fe7-2d4e5b9fd715.png)](http://jsdo.it/cx20/ahsW)|[![image](https://user-images.githubusercontent.com/1833979/37563035-d720e576-2aba-11e8-8c97-eeda01094a5f.png)](http://jsdo.it/cx20/MNU4)|

**Comment by willeastcott** [comment]
This is a problem with any glTF generated by the Three exporter when loaded into PlayCanvas. So it's a different problem. I noticed it last week. I'll see if I can figure out what's going on.

**Comment by willeastcott** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/697563/37569763-4c05303e-2aa4-11e8-8dbf-3cd8e46b8851.png)
