### ISSUE TITLE
2CylinderEngine.gltf is not displayed

### ISSUE THREAD

**Issue by cx20** [playcanvas/playcanvas-gltf#2]
Seems that some models can not be displayed in both Embedded and Binary glTF formats.

[2CylinderEngine.gltf](https://cx20.github.io/gltf-test/examples/playcanvas/index.html?category=sampleModels&model=2CylinderEngine&scale=0.005&type=glTF-Embedded)
![image](https://user-images.githubusercontent.com/1833979/34916822-6f257622-f981-11e7-8cf4-e2d855ba454b.png)

[ReciprocatingSaw.gltf](https://cx20.github.io/gltf-test/examples/playcanvas/index.html?category=sampleModels&model=ReciprocatingSaw&scale=0.01&type=glTF-Embedded)
![image](https://user-images.githubusercontent.com/1833979/34916823-73cc237e-f981-11e7-9200-0269d7326f0b.png)

[GearboxAssy.gltf](https://cx20.github.io/gltf-test/examples/playcanvas/index.html?category=sampleModels&model=GearboxAssy&scale=1&type=glTF-Embedded)
![image](https://user-images.githubusercontent.com/1833979/34916824-78d2d2b4-f981-11e7-9626-ee324142ecff.png)

[Buggy.gltf](https://cx20.github.io/gltf-test/examples/playcanvas/index.html?category=sampleModels&model=Buggy&scale=0.02&type=glTF-Embedded)
![image](https://user-images.githubusercontent.com/1833979/34916827-7d623f36-f981-11e7-8bb8-a2377cec87ba.png)

**Comment by cx20** [comment]
When I updated the library (PlayCanvas.js, gltf-loader.js, orbit-camera.js) and example code, several models are now displayed.

|model |result |
|:-----------------|:----------------:|
|[2CylinderEngine.gltf](https://cx20.github.io/gltf-test/examples/playcanvas/index.html?category=sampleModels&model=2CylinderEngine&scale=0.005&type=glTF-Embedded) |:x:               |
|[ReciprocatingSaw.gltf](https://cx20.github.io/gltf-test/examples/playcanvas/index.html?category=sampleModels&model=ReciprocatingSaw&scale=0.01&type=glTF-Embedded)|:white_check_mark:|
|[GearboxAssy.gltf](https://cx20.github.io/gltf-test/examples/playcanvas/index.html?category=sampleModels&model=GearboxAssy&scale=1&type=glTF-Embedded)             |:white_check_mark:|
|[Buggy.gltf](https://cx20.github.io/gltf-test/examples/playcanvas/index.html?category=sampleModels&model=Buggy&scale=0.02&type=glTF-Embedded)                       |:white_check_mark:|

However, 2CylinderEngine.gltf is not yet displayed. Is this because the usage is incorrect?

**Comment by willeastcott** [comment]
If I do a fresh checkout of the playcanvas-gltf repo and run the viewer, if you drag in 2CylinderEngine.gltf, you can see the model:

![image](https://user-images.githubusercontent.com/697563/35053168-3db6f672-fb5e-11e7-8766-a9389dd0775e.png)

**Comment by willeastcott** [comment]
That particular model is very large. I had to add code to the orbit-camera.js script to set near/far clip planes to properly enclose the model based on bounding box size.

**Comment by cx20** [comment]
I confirmed that it is correctly displayed in the viewer.

**Comment by willeastcott** [comment]
Looks like you have not updated your orbit-camera.js to the updated version in this repo.

**Comment by cx20** [comment]
Thanks to your advice I was able to notice the mistake in the library path.
I confirmed that the sample of [gltf-test](https://cx20.github.io/gltf-test/) is displayed without problems.
![image](https://user-images.githubusercontent.com/1833979/35099894-07ca74c2-fc9d-11e7-9980-53a2b21e63af.png)
