### ISSUE TITLE
Error in loadGlb function on Android 6.0 or older systems

### ISSUE THREAD

**Issue by derickwelman** [playcanvas/playcanvas-gltf#21]
I've tried to load a GLB file and it only works on Android 7.0 or newer.
When the function "loadGlb" is called with a GLB array buffer, the Android OS fires an error:

`Uncaught TypeError: First argument to DataView constructor must be an ArrayBuffer`
     `at new DataView()`
     `at loadGlb(line1280:24)`

It simply don't recognize the array buffer passed and consider it as null

By testing with other devices, i found out that is related with WebGL2 support. All Androids 6.0 or older don't present this support

OBS: On Android 7.0, newer versions and computer works normally

This project shows the problem
> https://playcanvas.com/project/545400/overview/test-gltf

**Comment by willeastcott** [comment]
Looks like you're not passing in an ArrayBuffer instance for the first argument to loadGlb.

**Comment by derickwelman** [comment]
finally, after 12 hour searching for clues of why it is not working i found out. I'm loading the GLB file from a server that uses SSL. Older Androids does'n complete the url with "https" if necessary, but the newer versions complete it. Adding this prefix to the player URL make the GLB to load properly.
Thanks for attention and sorry for my mistake.

**Comment by willeastcott** [comment]
No problem. I'm glad you tracked down the problem. 👍

**Comment by gokulsukumar03** [comment]
can you please give the sample  for loading GLB in android.

**Comment by willeastcott** [comment]
@gokulsukumar03 It's the same code for Android as on any other system.
