### ISSUE TITLE
Texture of BoxTexturedNonPowerOfTwo.gltf is not displayed correctly

### ISSUE THREAD

**Issue by cx20** [playcanvas/playcanvas-gltf#3]
I tried to display [BoxTexturedNonPowerOfTwo.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BoxTexturedNonPowerOfTwo).
However, it seems that textures that are not powers of two are displayed correctly.

https://cx20.github.io/gltf-test/examples/playcanvas/index.html?category=sampleModels&model=BoxTexturedNonPowerOfTwo&scale=1&type=glTF-Embedded

**Comment by willeastcott** [comment]
Can you elabourate on what is wrong with the render?

![image](https://user-images.githubusercontent.com/697563/35023177-6190617a-faee-11e7-86ed-c08975c00615.png)

**Comment by cx20** [comment]
Hmm. I have not been able to grasp the cause yet, but in some cases it can be displayed by reloading (Ctrl + R) with the Chrome browser.

![image](https://user-images.githubusercontent.com/1833979/35045347-ea1135ae-fbd6-11e7-9b3a-ce4a01883bf1.png)

![image](https://user-images.githubusercontent.com/1833979/35045320-cb11b96c-fbd6-11e7-987f-c003612b265a.png)

When it can not be displayed, the following warning is output to the console.

```
RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
```

Test environment:
ThinkPad X260 + Intel(R) HD Graphics 52 + Windows 10 + Chrome 63.0.3239.132

**Comment by cx20** [comment]
I confirmed that it is displayed correctly with the latest version of glTF Loader.
https://cx20.github.io/gltf-test/examples/playcanvas/index.html?category=sampleModels&model=BoxTexturedNonPowerOfTwo&scale=1&type=glTF-Embedded
