### ISSUE TITLE
glTF animation will result in an error

### ISSUE THREAD

**Issue by cx20** [playcanvas/playcanvas-gltf#33]
I tried displaying the glTF animation model in [gltf-test](https://github.com/cx20/gltf-test).
However, it seems that an error occurs when trying to display it using the latest [playcanvas-anim.js](https://github.com/playcanvas/playcanvas-gltf/tree/master/src).

Below is the display result of BrainStem.gltf.
https://cdn.rawgit.com/cx20/gltf-test/73431dfccfa70cb753c615079c8b8f77a55d4375/examples/playcanvas/index.html?category=sampleModels&model=BrainStem&scale=1&type=glTF

```
playcanvas-anim.js:883 
Uncaught ReferenceError: clip is not defined
    at AnimationClip.getAnimTargets (playcanvas-anim.js:883)
    at AnimationSession.play (playcanvas-anim.js:1519)
    at AnimationClip.play (playcanvas-anim.js:902)
    at AnimationComponent.playClip (playcanvas-anim.js:1671)
    at loadGltf.decoderModule (index.js:199)
    at playcanvas-gltf.js:1343
    at parse (playcanvas-gltf.js:1198)
    at playcanvas-gltf.js:1334
    at XMLHttpRequest.xhr.onload (playcanvas-gltf.js:1184)
```

**Comment by willeastcott** [comment]
CC @thomasbiang

**Comment by kungfooman** [comment]
Buggy function looks like this:

```js
// a dictionary: retrieve animTargets with curve name
AnimationClip.prototype.getAnimTargets = function () {
    var animTargets = {};
    for (var i = 0, len = this.animCurves.length; i < len; i++) {
        var curve = clip.animCurves[i];
        var curveTarget = curve.getAnimTargets();
        animTargets[curve.name] = curveTarget[curve.name];
    }
    return animTargets;
};
```

Just fix this:

```JS
        var curve = clip.animCurves[i]; // bug, clip not defined
        var curve = this.animCurves[i]; // fix, clip == this
```

👌

**Comment by willeastcott** [comment]
Thanks @kungfooman!! 😄

**Comment by cx20** [comment]
I confirmed that the problem was solved with the latest version.
https://cdn.rawgit.com/cx20/gltf-test/b1aa8e281d58b60aa3ce12bbceefcc96fbf84da0/examples/playcanvas/index.html?category=sampleModels&model=BrainStem&scale=1&type=glTF
