### ISSUE TITLE
Lightmap Texture Support

### ISSUE THREAD

**Issue by MackeyK24** [playcanvas/playcanvas-gltf#39]
Hey @willeastcott  I am trying to add lightmap support to gltf.

Is there some SPECIAL format lightmap png needs to be in ... I am trying to use a lightmap generated from Unity.

Here is Lightmap Texture:

![testscene_lightmap-0_comp_light](https://user-images.githubusercontent.com/5013415/46656707-64905880-cb4a-11e8-8ddc-a3e1e5051297.png)

I am trying to load in gltf like so:

```
        if (data.hasOwnProperty('commonConstant') && data.commonConstant.hasOwnProperty('lightmapTexture')) {
            var lightmapTexture = data.commonConstant.lightmapTexture;
            material.lightMap = resources.textures[lightmapTexture.index];
            //material.lightMapChannel = 'rgb';
            if (lightmapTexture.hasOwnProperty('texCoord')) {
                material.lightMapUv = lightmapTexture.texCoord;
            } else {
                material.lightMapUv = 1;
            }
            if (lightmapTexture.hasOwnProperty('extensions') && lightmapTexture.extensions.hasOwnProperty('KHR_texture_transform')) {
                var lightmapTransformData = lightmapTexture.extensions.KHR_texture_transform;
                if (lightmapTransformData.hasOwnProperty('scale')) {
                    material.lightMapTiling = new pc.Vec2(lightmapTransformData.scale[0], lightmapTransformData.scale[1]);
                }
                if (lightmapTransformData.hasOwnProperty('offset')) {
                    material.lightMapOffset = new pc.Vec2(lightmapTransformData.offset[0], lightmapTransformData.offset[1]);
                }
            }
        }

```

And the GLTF Material Snippet:

```
    {
      "pbrMetallicRoughness": {
        "metallicFactor": 0.0,
        "roughnessFactor": 0.5
      },
      "commonConstant": {
        "lightmapTexture": {
          "index": 1,
          "texCoord": 1,
          "extensions": {
            "KHR_texture_transform": {
              "offset": [
                0.239268735,
                0.7841906
              ],
              "scale": [
                0.238089427,
                0.238089427
              ],
              "texCoord": 1
            }
          }
        },
        "extras": {
          "metadata": {
            "hdrpacking": "none"
          }
        }
      },
      "name": "Default-Material.Instance.00d31c29005a4668a044cb688552a494",
      "extras": {
        "metadata": {
          "glossyreflections": true,
          "specularhighlights": true
        }
      }
    }

```

But it does not look right... It should look like this:

![screen shot 2018-10-08 at 10 37 36 pm](https://user-images.githubusercontent.com/5013415/46656919-d23c8480-cb4a-11e8-9b24-f62c12312bf7.png)

But instead it looks like this:

![screen shot 2018-10-08 at 10 37 19 pm](https://user-images.githubusercontent.com/5013415/46656933-da94bf80-cb4a-11e8-9b42-5f7ab871ce0d.png)

I dont see any of the shadows baked into the lightmap texture... What am i doing wrong with lightmaps in PlayCanvas ???

**Comment by guycalledfrank** [comment]
Unity and WebGL may have different conventions regarding the orientation of the texture. Can you try flipping the texture vertically?

**Comment by MackeyK24** [comment]
I tried Flipping Texture and ALSO GLTF flips the by -OFFSET Y... So that would take care of FLIPPING or NOT FLIPPING the texture but flip offset Y instead...

But both ways DIDNT HELP... The ground should be showing the shadow map...

I noticed in BabylonJS for my to use the lightmap.. we have to set a property on the material.useLightmapAsShadowMap = true...

Do you know of any type of equivalent property for PlayCanvas to use lightmap ???


And to clearify... IS there anything special about the LightmapTexture that is used inPlayCanvas or should the texture shown above work in PlayCanvas ???

**Comment by MackeyK24** [comment]
Yo @willeastcott 

It seems that SOME coloring from lightmap is there, but for some reason NONE of the BAKED shadows from the Lightmap Show up in PlayCanvas...

Shouldn't those BAKED shadows from lightmap show up ???

**Comment by MackeyK24** [comment]
Or if PlayCanvas can use Lightmaps like that... For Global Illumination as well as BAKED SHADOWS ???

**Comment by guycalledfrank** [comment]
If you can share this scene somewhere, I'll debug. Hard to say what's wrong based on these pics.

**Comment by MackeyK24** [comment]
Yo @guycalledfrank 

Here is what the scene should look like:

![screen shot 2018-10-10 at 3 56 47 am](https://user-images.githubusercontent.com/5013415/46741474-ccc16600-cc40-11e8-95a8-0f7ab4c7a66e.png)

Here is what it looks like in my playcanvas project:

![screen shot 2018-10-10 at 3 57 04 am](https://user-images.githubusercontent.com/5013415/46741504-dea30900-cc40-11e8-96b2-2fd28a920ec7.png)

Here is a zip file with the Test Project you can pick apart and debug... The textures are under the scene/assets folder

[TestScene.zip](https://github.com/playcanvas/playcanvas-gltf/files/2464954/TestScene.zip)


But just to clarify... WE SHOULD BE SEEING THE BAKED SHADOWS RIGHT???

I mean thats what the Lightmap Is Supposed to show... All the STUFF baked into lightmap texture.

If so... you can see the TWO BOX Shape shadows on the actual lightmap texture, they just dont showup on the GROUND PLANE


Thanks sooooo much for taking a look at :)

**Comment by guycalledfrank** [comment]
OK, so:

- You have complete direct lighting in your lightmap. But you also create a dynamic directional light that shines brightly on top of it. Cubes have castShadows disabled, so you get realtime shadowless directional lighting.
`pc.app.root.findByName("Directional Light").enabled = false`

- Your meshes don't have secondary UV channel. By default PlayCanvas assumes lightmaps using UV1, not UV0. Therefore lightmap is simply disabled. You can set lightMapUv = 0 to use UV0.
```
pc.app.root.findByName("Plane").model.meshInstances[0].material.lightMapUv = 0;
pc.app.root.findByName("Plane").model.meshInstances[0].material.update();
```

- Lightmap shadows should now appear on the plane, but their coordinates are wrong. It appears that your offset/tiling values are not correct. 
`pc.app.root.findByName("Plane").model.meshInstances[0].material.lightMapOffset = new pc.Vec2(0,1-0.78125)`
This value seems to work.

**Comment by MackeyK24** [comment]
Yo @guycalledfrank ... Thanks SOOOOOO much for the info. I will check into each of these issues.

But first... I guess PlayCanvas uses lightmaps a bit different than BabylonJS. First off... Uing the same DIRECT/INDIRECT lighting options from Unity and the same lightmap... BabylonJS you still use runtime / realtime lights... Especially for cast realtim shadows that might be in the scene ALONG WITH THE BAKED SHADOWS from the lightmap... I thnk the material.useLightmapAsShadowMap might have something to do with this feature...

But you are saying in PlayCanvas if you are using Lightmaps (Direct) you SHOULD NOT use realtime lights as well... Well if that is so how would have BOTH realtime shadows on a few items that move but use BAKED lightmaps on all other object that dont move.

**Comment by MackeyK24** [comment]
Yo @guycalledfrank ...

you said this:

Lightmap shadows should now appear on the plane, but their coordinates are wrong. It appears that your offset/tiling values are not correct.
pc.app.root.findByName("Plane").model.meshInstances[0].material.lightMapOffset = new pc.Vec2(0,1-0.78125);
pc.app.root.findByName("Plane").model.meshInstances[0].material.update();


So what are you just using 1 minus whatever i had for offset (0.78125) ???

**Comment by MackeyK24** [comment]
Yo @guycalledfrank ... Thanks Again...

Hey man do you think you could OUTLINE that shader code you were talking about to try and get some kind of mixed baked and real time light solution...

Or Better Yet... You wanna work with on my WebGL Canvas Tools Project ???

I can send you the Unity Project and make a Video for you exlplain everything... then we could work together and get this thing finish and made available for the PlayCanvas Community :)

**Comment by guycalledfrank** [comment]
>Or Better Yet... You wanna work with on my WebGL Canvas Tools Project ???
No, sorry, I'm busy doing [other cool stuff](https://forum.unity.com/threads/bakery-gpu-lightmapper-v1-3-released.536008/) :)

As for outlining, how about baking lightmaps in the shadowmask mode? You should get 2 textures, indirect + static shadows. It's a good starting point for fast high quality mixing. Set the indirect lightmap as usual, then pass the mask as a custom parameter (e.g. material.setParameter).
In PlayCanvas you can also override different chunks of the standard shader with your custom code. I saw you were using VSM16 shadow mode. Here is some of its code: https://github.com/playcanvas/engine/blob/master/src/graphics/program-lib/chunks/shadowEVSM.frag
You can copy it and let it read the shadowmask in the VSM function, multiply it by existing calculateEVSM() call and return. This way you'll get static shadowmask mixed with dynamic VSM shadows.
The overriding syntax is simple:
`material.chunks.shadowEVSMPS = yourVersionOfThisCode;`

**Comment by MackeyK24** [comment]
Yo @guycalledfrank ... Dude.. You ARE DA SHIT :)

That makes perfect sense... I was wondering what you do with shadowMask texture... I will look into that as a solution... Thanks again Bro :)

**Comment by MackeyK24** [comment]
Hey @guycalledfrank ... How did you even come up with the 1 - 0.78125 for the offset Y. 

Unity and Babylon js export use the exact offsetX and offsetY from the Baked Light Map Settings.
In unity the offset for X and Y for the "Plane" lightmap texture is ZERO. Why would PlayCanvas use different values lightmap texture offset.

And the 0.78125 is the actual scaling of the lightmap in the texture... The offset should be ZERO... Why would that number have anything to do with offset.

And @willeastcott maybe you can chime in here as well...

I just dont uderstand the rtyme or reason of the OFFSET X and Y for PlayCanvas Lightmaps... Can you help me understand whats going on there. 

i got the lightmaps and shadowmask exporting out of Unity i just need a bit more help getting PlayCanvas to use them right... I really appreciate all your help :)

**Comment by guycalledfrank** [comment]
Just looking at your lightmap, it looks like the plane should have an offset:

![image](https://user-images.githubusercontent.com/7008423/46800363-15bc0c00-cd60-11e8-806e-45a211a46a7d.png)


Perhaps the texture actually needs to be flipped AND UVs need to be flipped vertically to avoid modifying the offset.

**Comment by MackeyK24** [comment]
I actually generate uvs2 by coping uvs1...

So your saying I could just flip those copied uvs2 and Flip vertically the lightmap textures and then the offset values would then match... so 0,0 would really be 0,0 and not have modify...

Also I noticed the Sketchfab exporter acutually use -offset.y for light maps.

It’s weird... some Unity GLTF exporter Do not flip uvs but flip the textures ... the original Khronos flips the uv coordinated and does not flip the texture... so I think I am coping flipped uvs1 over to uvs2... I will try reverse that for lightmap uvs2

**Comment by MackeyK24** [comment]
Got Damm @guycalledfrank ... Again... YOU ARE DA SHIT :)

That was it exactly... I was Flipping the UV1 and NOT Flipping Texture (thats how Khronos UnityGLTF Export Process works)... 

So i DONT FLIP UV2... But instead Flip Texture (For Lightmaps Only)... And its freaking sweet...

Global Illumination Baked and Shadows Baked... No Directional Light in scene at ALL...

![screen shot 2018-10-11 at 5 38 45 am](https://user-images.githubusercontent.com/5013415/46816364-86d7d100-cd18-11e8-8b8a-6497ba95d780.png)


Thanks again... Soooooo Much...

P.S. 

I am going to setup all the Shader Chuck stuff in my playcanvas-gltf.js and i now ALSO export the ShadowMask texture. Can you please (When you get a chance) show me how or what i need to do in the shader chunk to handle Mixed Lights ... Ideally i would to handle BOTH subtractive and shadowmask mixed lights... But at least try get shader mask for mixed lights first....

Thanks Again Man... I mean it... You are DA SHIT :)

**Comment by willeastcott** [comment]
Seems solved so I'm gonna close. 😄

**Comment by MackeyK24** [comment]
Hey @willeastcoot you want me to PR lightmap support. It is based off KHR_common_materials ... PBR create constant lightmap texture

**Comment by willeastcott** [comment]
I don't see that extension [here](https://github.com/KhronosGroup/glTF/tree/master/extensions).

**Comment by MackeyK24** [comment]
Maybe it has not gone public yet... But WE DO use in in UnityGLTF to export lightmaps

Per: stevenvergenz commented on Jun 2, 2017

I've added a tentative lightmap implementation to the commonConstant material in UnityGLTF, since we use pre-computed lighting more routinely than PBR. What it looks like:
{     
"alphaMode" : "MASK",     
"doubleSided" : true,     
"emissiveFactor" : [         0.0,         1.0,         0.0     ],     
"emissiveTexture" : {         "index" : 1     },     
"name" : "Material",     
"commonConstant" : {         
  "lightmapTexture": {            
  "index": 0,            
  "texCoord": 1         
} 
} }
--

**Comment by MackeyK24** [comment]
That sounds great... where do we start

**Comment by MackeyK24** [comment]
Hey @willeastcott or @guycalledfrank ... Can you please help me FIX the lightmap vs real time light precedence issue.

It seems the REALTIME lights OVERWRITE or SHINE ON TOP of the the lightmap colors. For both global illumination and baked shadows. It would seem that the lightmap should take precedence over realtime lights... Or BLEND in those pixels AFTER the realtime light... or something so the that the realtime lights does NOT negate the global illumination and baked lights by shining OVER TOP.

There has got to be some kind of shader chunk (like i did for specular glossiness) to ALTER the rendering so the the lightmaps take precedence... If one of you can PLEASE help me figure that part out i can release my first beta of the WebGL Canvas Tools (Unity Based GLTF Scene Exporter with Extra Metadata) for the community.

I know you guys are busy,  but any help would greatly appreciated :)

**Comment by MackeyK24** [comment]
light.mask seems like that might work. Question:

if i set mesh instance.mask = 2 for those that have static lightmaps... What value would i set on the camera to to see both mask 1 and 2 (so the camera sees both lightmap and non-lightmap)

???

**Comment by guycalledfrank** [comment]
These are bits, so 1|2

**Comment by MackeyK24** [comment]
Yo @guycalledfrank ... Hey man thanks for the light.mask suggestion. But its not going to work.
What if i have static scenery with lightmaps... then i had a realtime character run by the static scenery... it would not catch the realtime shadow on the static scenery.

I am going to need to do a proper lightblend.
Can you please OUTLINE which shader chunks i need to mess with to get realtime and lightmap light blending.

**Comment by kungfooman** [comment]
@MackeyK24 Can't you just release the current WebGL Canvas Tools Project already? I used Unity "as programer" (e.g. writing custom animated model format loaders) for years so I might be able to figure some stuff out regarding the lightmap mixing/blending aswell. I would really like to have a 2nd exporter next to Blender, because Unity/C# is way easier than Blender/Python.

**Comment by MackeyK24** [comment]
Yo @kungfooman ... I am not really ready to go public like that. Still in early feature development.

But if you wanna help me work on the project, i will send you ca copy of my whole project (including my PlayCanvas-Tools typescript project)

Let me know :)

**Comment by kungfooman** [comment]
Yo @MackeyK24, I'm actually interested ^^ I hope your code works with Unity 2018

Might wanna join https://discordapp.com/invite/N67tQuU for chat/discussion?

**Comment by MackeyK24** [comment]
Wow... that shader chunk debugging system is the shizzz-nit 

I ripped that mam fam out the viewer and tweaked a bit to work with host project that my WebGL Canvas Tools uses 

It’s freaking awesome...

Yo @kungfooman ... I make a project with lights maps and real-time lights .... please see if you can handle blending the lights like was suggested above using my implementation of the new shader chunk system

Kuddos to WHOEVER added that feature to the viewer 👍

**Comment by MackeyK24** [comment]
And yes @kungfooman ... my WebGL Canvas Tools works with 2018 ... I even tested it against the new 2019 Alpha

**Comment by MackeyK24** [comment]
Can you contact me at MackeyK24@gmail.com so we can hook up

**Comment by MackeyK24** [comment]
YO @kungfooman ...

Here is a test mixed lights project
https://github.com/MackeyK24/MackeyK24.github.io/tree/master/mixedlights

can also just run it with:
https://mackeyk24.github.io/mixedlights

The Sphere and the Cube on the LEFT are using Real-Time shadows...
The Sphere and the Cube on the RIGHT are using Baked shadows via a lightmap...

But PlayCnvas does not Blend mixed lights well as you know... Hopefully you can mess around with the shader chunks and figure the the Shader Blending @willeastcott  was talking about.

FYI this is what is SHOULD look like:

![screen shot 2018-11-09 at 8 24 10 pm](https://user-images.githubusercontent.com/5013415/48298281-fdbed180-e45e-11e8-8fdb-beb14c48d558.png)


But this is what i get (Look like the realtime light is canceling out they shadows completely)

![screen shot 2018-11-09 at 8 24 43 pm](https://user-images.githubusercontent.com/5013415/48298289-1b8c3680-e45f-11e8-85b5-e6bec5833fda.png)

Can you PLEASE try and fix ... Anyone else can also download the project and or just load from the github.io pages and play with Shader Chunks: https://mackeyk24.github.io/mixedlights

**Comment by MackeyK24** [comment]
ALSO... This is if i remove the lightmap, the realtime shadows show up:

![screen shot 2018-11-09 at 8 45 06 pm](https://user-images.githubusercontent.com/5013415/48298382-a28dde80-e460-11e8-9b39-f69b5892e1df.png)


This is if i LOWER or REMOVE the realtime lighting, then the baked shadows show up: 

![screen shot 2018-11-09 at 8 46 26 pm](https://user-images.githubusercontent.com/5013415/48298403-de28a880-e460-11e8-89d8-13d1d31473e8.png)


So you can have either FULL REAL-TIME LIGHTING or FULL BAKED LIGHTING...

But just can have mixed... And i really dont understand the POINT of BAKED lighting if you CANT ALSO have mixed lights.... OTHERWISE EVERYTHING in the scene would have to STATIC and NOTHING could ever move... Is that correct ??? (Pinging @willeastcott)

**Comment by guycalledfrank** [comment]
Lightmaps are added on top of real-time lighting, so everything will get brighter. Same thing would happen in Unity. If you can share your Unity project, I'll tell you exactly what's the difference.

**Comment by kungfooman** [comment]
To use the shader chunk live editor for shadow mapping debugging the directional light shader needs to be updated, maybe you wanna update the code:

```JS

light = pc.app.root.children[1];
light_pivot = light.children[0];

ShaderChunks.prototype.regenerateShaders = function() {
    console.log("regenerate shaders...");
    pc.app.graphicsDevice.programLib._cache = {};
    light_pivot.light.refreshProperties();
    if (window.meshes == undefined || window.meshes == null) {
        console.warn("No winow mesh instances found");
        return;
    }
    var n = window.meshes.length;
    for (var i=0; i<n; i++) {
        var meshInstance = window.meshes[i];
        meshInstance.material.clearVariants();
    }
}

```

(or just execute that in devtools)

Nice to test with the directional light intensity:

```JS
light_pivot.light.intensity = 0 // only baked lights visible
light_pivot.light.intensity = 0.6 // baked lights start to fade out
light_pivot.light.intensity = 200 // only vsm visible
```

That is enough to start live editing the GLSL stuff, I am just experimenting around myself currently

**Comment by MackeyK24** [comment]
> Lightmaps are added on top of real-time lighting, so everything will get brighter. Same thing would happen in Unity. If you can share your Unity project, I'll tell you exactly what's the difference.

Unity mixed light works perfect and NOT DOUBLE lighting... Here is a shot from unity using mixed lighting:

![48298281-fdbed180-e45e-11e8-8fdb-beb14c48d558](https://user-images.githubusercontent.com/5013415/48301477-e39ee680-e492-11e8-8583-90dd43547c95.png)

I also dont think the LIGHT-MAP is on top of the real-time... Otherwise i should see the BAKED shadows from the lightmap texture

**Comment by MackeyK24** [comment]
Yo @kungfooman ... I added support for ALL debug lights to refresh properties:

```
ShaderChunks.prototype.regenerateShaders = function() {
    console.log("Regenerating shaders...");
    pc.app.graphicsDevice.programLib._cache = {};
    if (window.hasOwnProperty("lights") && window.lights != null) {
        var n = window.lights.length;
        for (var i=0; i<n; i++) {
            var lightPivot = window.lights[i];
            lightPivot.light.refreshProperties();            
        }
    }
    if (window.hasOwnProperty("meshes") && window.meshes != null) {
        var nn = window.meshes.length;
        for (var ii=0; ii<nn; ii++) {
            var meshInstance = window.meshes[ii];
            meshInstance.material.clearVariants();
        }
    }
}
```

**Comment by guycalledfrank** [comment]
>I also dont think the LIGHT-MAP is on top of the real-time... Otherwise i should see the BAKED shadows from the lightmap texture

How do you think it mixes it then? Unity knows has just 3 modes to date:
- Indirect is baked, direct is fully realtime.
- Indirect AND static shadows are baked (2 separate maps), dynamic light and shadows from dynamic (only) objects are realtime.
- Main shadow color is user-specified, and dynamic shadows are blended with a single lightmap by first subtracting this color to get an approximate baked shadows mask.

Do you have an indirect only lightmap? Do you have a shadow mask? Do you have main shadow color? You need one of them in order to blend. Share your scene and I'll tell you what mode is used there.

**Comment by kungfooman** [comment]
Quite funny, I tried to solve it all the way via some GLSL coding, but that helped me to realize what actually happens. So the lightmap is already pretty whitish and when your red directional light *adds* to it, it clamped at [1,1,1], so nothing changes anymore... and that of course can be fixed via tone mapping:

```
pc.app.scene.toneMapping = 1
```

![lightmap_tonemap](https://user-images.githubusercontent.com/5236548/48305010-cb2adc80-e523-11e8-9e66-259d41fdeb14.png)

Or some other for testing:

```JS
pc.app.scene.exposure =  0.2
pc.app.scene.toneMapping = 4
```

![lightmap_tonemap_2](https://user-images.githubusercontent.com/5236548/48305129-9ae43d80-e525-11e8-8768-413dd1ed9166.png)

**Comment by MackeyK24** [comment]
Yo @guycalledfrank ... I am using single Intensity map with mixed light set to subtractive:

![screen shot 2018-11-10 at 2 00 27 pm](https://user-images.githubusercontent.com/5013415/48307461-14156d80-e4f1-11e8-9bd9-e6f4ec16f393.png)

![screen shot 2018-11-10 at 2 00 46 pm](https://user-images.githubusercontent.com/5013415/48307462-18418b00-e4f1-11e8-9d59-8ef8529ddc69.png)

So in your opinion... Do you think this is something we can do in PlayCanvas (Like Unity does mixed lights). If so... And you are willing to help work on this with me and @kungfooman , i will send you a copy of my project. Its in very early dev stages right now and i didnt want to public share and have a bunch of copies out there yet. But if you are going to help make this happen, and you send me your email address... I will email you and @kungfooman a link to download the raw unity project.

**Comment by MackeyK24** [comment]
Man this is getting weird... I put together a CLEAN Unity Project... Starting Project in Unity 2018.2.15f1

Using NO IBL and Grey Ambient Color.

![screen shot 2018-11-10 at 3 11 11 pm](https://user-images.githubusercontent.com/5013415/48307893-e7665380-e4fa-11e8-9091-2f19a6d02258.png)

Also the Scene Controller uses this Init Code:

```
/**
 * Backing Script Class
 * @class SkyboxController
 */
@createScript()
class SkyboxController extends CanvasScript implements ScriptType {
   
    public initialize():void {
        console.log("Intializing scene controller...");
        this.app.scene.exposure = 1;
        this.app.scene.toneMapping = pc.TONEMAP_LINEAR;
        this.app.scene.gammaCorrection = pc.GAMMA_SRGB;
    }
}
```

But is seems to be working **BETTER**, But i have not changed much (Just Ambient Color).

But i am at least hopeful that MIXED lights can be PlayCanvas... Just don quite understand the RYHME or REASON as to why sometimes it shows up and sometimes it does not... Sometimes it has DOUBLE lighting color (MUCH DARKER) and sometimes it does not... 

It must have to do with the Light Color, Ambient Color, Tone Mapping, Color Correction and Exposure... But i need to be sure what has what effect.

I hope you guys @guycalledfrank  and @kungfooman can help work on this... 

@kungfooman ... I got your email, will be sending you project soon.

@guycalledfrank ... Please send me your email and i will send you project as well.

And please DONT put out a bunch of copies of project as again, i am in early stages of
my **WebGL Canvas Tools** and dont quite know how i am going to release EVERYTHING... Or even **IF** i am going to release ANYTHING... 

IF i cant make a reliable toolkit to export unity content to GLTF and use PlayCanvas to create games using that exported Unity Content... I probably going to abandon this whole Unity GLTF Scene Exporting and just go with Unreal Engine or something like that.

So please let me know if you will help be a **WebGL Canvas Tools** developer 👍

**Comment by MackeyK24** [comment]
Yo @kungfooman ... Without any Shader mods....

just these settings:

        this.app.scene.exposure = 1;
        this.app.scene.toneMapping = pc.TONEMAP_LINEAR;
        this.app.scene.gammaCorrection = pc.GAMMA_SRGB;

So tonemapping to Linear i get this (Which looks pretty good)

![screen shot 2018-11-10 at 9 06 32 pm](https://user-images.githubusercontent.com/5013415/48310142-ecdc9180-e52c-11e8-8b82-636584c8561e.png)

The TWO left shadows are REALTIME and the the two Right shadows are BAKED...

And NO DOUBLE Lighting... Now im really confused as to what makes MIXED lights work...

This run is has no Shader mods and Exposure = 1, toneMapping = Linear and gammaCorrection SRGB

BUt again that look pretty freaking good... I just dont know for SURE as to WHY (Exactly) they are working (For the most part)

What do you think @guycalledfrank

**Comment by guycalledfrank** [comment]
OK, actually your Lighting settings from Unity are enough to figure it out. The "realtime shadow color" is the key here. It's a rather cheap mixing mode with an assumption that this single color will always resemble the actual baked shadow color, so it can be subtracted from the lightmap.

What they do is:

`min(lightmap, max(shadowColorConstant, lightmap - saturate(dot(normal, lightDir)) * (1-realtimeShadow) * realtimeLightColor))`

**Comment by guycalledfrank** [comment]
How about this:

`lighting = lightmap - saturate(dot(normal, realtimeLightDir)) * realtimeLightColor * (1-realtimeShadow)`

**Comment by MackeyK24** [comment]
> How about this:
> 
> `lighting = lightmap - saturate(dot(normal, realtimeLightDir)) * realtimeLightColor * (1-realtimeShadow)`

So is this code for a shader chunk or just some pseudo code o say what should be happening.

IIf i can use this code directly in a shader chunk... Which one ???

**Comment by MackeyK24** [comment]
So 'realtimeShadow' is the Realtime Shadow Color from the the Unity
Subtractive Settings... So i can just pass that color to a shader chunk
just like any other color on the material then update the some shader
chunk.... Which shader chunk ???

**Comment by guycalledfrank** [comment]
It's a pseudocode. Realtime shadow is what the VSM function returns.

**Comment by MackeyK24** [comment]
So do you wanna help implement this stuff in the Shaders ?

**Comment by MackeyK24** [comment]
What if i use the Realtime Shadow Color from Unity... I serialize that
color along with lightmap texture to use in the gltf parser.

If i do that, What Shader would i have to modify ???

**Comment by MackeyK24** [comment]
> How about this:
> 
> `lighting = lightmap - saturate(dot(normal, realtimeLightDir)) * realtimeLightColor * (1-realtimeShadow)`

Yo @kungfooman ... Do you think you could use this pseudo code to update the necessary shader chunks... I dont know all the Shader Chunk stuff i need to be able to implement

**Comment by MackeyK24** [comment]
Yo @kungfooman ... I update the project at https://mackeyk24.github.io/mixedlights

Source: https://github.com/MackeyK24/MackeyK24.github.io/tree/master/mixedlights

I am spinning BOTH cubes to show Realtime Shadow On Left Cube and even though im spinning the right cube as well... it shows the BAKED static shadow not moving...

The shadow colors look a little off, but if you could implement pseudocode @guycalledfrank outlined in your Shader Chunk System.... That would be freaking awesome 👍

**Comment by MackeyK24** [comment]
Paging @kungfooman and @guycalledfrank ... Do you guys still think you can help with the mixed lights problem.

@guycalledfrank gave us the pseudo code:

lighting = lightmap - saturate(dot(normal, realtimeLightDir)) * realtimeLightColor * (1-realtimeShadow)

but i dont know enough about the shader chunk system to implement by myself. I dont know how to read other shader chunk return values... Like how to get the realtim shadow color in the getAlbedo section of the shader chunk.

Can you please help ???

**Comment by kungfooman** [comment]
Since you don't release the exporter nobody can play/test around with it freely, the tool could probably already have a smallish community of contributors for problems like this one

**Comment by MackeyK24** [comment]
Im not quite ready for PUBLIC release. But if you send me your real email address. I will give you a copy , in its current state for you to play around with and HELP ME with the mixed lights shader.

I already packaged it up for you. I just need to know where to send it :)

**Comment by MackeyK24** [comment]
Again... Its not ready for PUBLIC release yet. I really need help with mixed lighting before i finalize on the architecture of the toolkit itself. Getting all the basics i want in there (HOW i do things in Unity and HOW i implement them in Playcanvas... WILL CHANGE ALOT at this stage of development)

But if it gets me your help... Here it is... 

(PLEASE CONTACT ME FOR A GOTOMEETING and i will show you how to use it)

Mackey Kinard
MackeyK24@gmail.com

[CanvasTools_Beta_1.unitypackage.zip](https://github.com/playcanvas/playcanvas-gltf/files/2648585/CanvasTools_Beta_1.unitypackage.zip)
