### ISSUE TITLE
Collision Mesh

### ISSUE THREAD

**Issue by pacasa2** [playcanvas/playcanvas-gltf#4]
Hi!
I am currently testing gltf loader in playcanvas.
I was wondering what would be the best way to attach a Mesh collision to the loaded Model, as GLTF models loaded in Runtime don't have pc.Assets.

I am not sure if this is feature that this loader should provide or developers have to calculate this mesh collider by themselves...
Anyway, I hope you can help me.
Thanks!

**Comment by willeastcott** [comment]
You can descend the entity hierarchy returned by the loaded. If you find an entity with a model component, just add a rigidybody and collision component and set the model component's model on the collision component.

**Comment by pacasa2** [comment]
Problem Solved!!
I was already doing that, but there was a problem with my scene hierarchy and collision didn't work properly..
Anyway, Thanks for the quick response!!
PS: Keep Working Hard on this Loader because it will be an awesome feature for PlayCanvas!!
