### ISSUE TITLE
Why did I load the Draco compressed model to report errors

### ISSUE THREAD

**Issue by gameatp** [playcanvas/playcanvas-gltf#53]

**Comment by kungfooman** [comment]
Can you explain more?

**Comment by gameatp** [comment]
I used Facebook's gltf converter to switch to a compressed gltf and report an exception after loading.
![image](https://user-images.githubusercontent.com/4427058/51094803-0b8c2c80-17eb-11e9-9d1d-46006d7ccd0b.png)
![image](https://user-images.githubusercontent.com/4427058/51094808-16df5800-17eb-11e9-93ed-d77bc886a8f7.png)
I don't know if there's a problem with parsing or a problem with Facebook's converter.

**Comment by gameatp** [comment]
[21003.zip](https://github.com/playcanvas/playcanvas-gltf/files/2753965/21003.zip)
This is the transformed model.

**Comment by kungfooman** [comment]
Your file works with: https://gltf.insimo.com/

But it fails with:

PlayCanvas
https://gltf-viewer.donmccurdy.com/
https://sandbox.babylonjs.com/

(I don't know why, just tested to figure out if the exporter is broken, but since it works on insimo, it should be broken draco/gltf importer)

**Comment by gameatp** [comment]
Yes, I just want to know which side of the problem is.

**Comment by gameatp** [comment]
> Your file works with: https://gltf.insimo.com/
> 
> But it fails with:
> 
> PlayCanvas
> https://gltf-viewer.donmccurdy.com/
> https://sandbox.babylonjs.com/
> 
> (I don't know why, just tested to figure out if the exporter is broken, but since it works on insimo, it should be broken draco/gltf importer)

Thank you. I've found the problem. The model data compressed by Draco is incorrect.

**Comment by willeastcott** [comment]
Great! I'm glad you found the problem. 👍
