### ISSUE TITLE
How to play back animation?

### ISSUE THREAD

**Issue by wei292224644** [playcanvas/playcanvas-gltf#58]

**Comment by kungfooman** [comment]
You can see the example code here, just search for `this.gltf.animComponent`: https://github.com/playcanvas/playcanvas-gltf/blob/master/viewer/src/viewer.js#L187

If you drag&drop a model with animations, you can also test via f12/devtools:

![gltf_animclips](https://user-images.githubusercontent.com/5236548/51252918-5483e280-199d-11e9-8d36-9903e67a4029.png)

Or e.g. just `viewer.gltf.animComponent.playClip("idle")`
