### ISSUE TITLE
Huge Garbage Collector times

### ISSUE THREAD

**Issue by kungfooman** [playcanvas/playcanvas-gltf#61]
I don't know yet what is causing these GC times, but I guess it's worth an investigation:

![gc](https://user-images.githubusercontent.com/5236548/51868400-42ffea80-234e-11e9-96af-4e0af6ee3255.png)

The smaller GC is already 17ms and the average complete frame time is ~110ms.

**Comment by kungfooman** [comment]
This is strange, I restarted Chrome and now the GC is non-existant anymore 🤔 

![chrome_restart](https://user-images.githubusercontent.com/5236548/51878620-93883f80-2370-11e9-9545-db680ad96e00.png)

Frame times dropped to 80-90ms/frame

**Comment by kungfooman** [comment]
The GC kinda shows up randomly, I don't know why that is.

In my local fork I just played around somewhat with the code base and I removed every `return [a, b]` tuple construct and it removed the GC overhead.

Basically I just saved one in the other, like

```JS
// return [a, b]
a.b = b;
return a;
```

**Comment by willeastcott** [comment]
Hmm. Good point.

Hey @thomasbiang - doing something like:

```
return [ a, b ];
```

...generates garbage. An alternative could be to pass in a results object to a function that is cached/reused. But maybe you have some ideas to avoid this allocation of transient arrays?
