### ISSUE TITLE
AnimationKeyable#clone ignores inTangent/outTangent

### ISSUE THREAD

**Issue by kungfooman** [playcanvas/playcanvas-gltf#64]
They are assigned here, for cubicspline curves only:

https://github.com/playcanvas/playcanvas-gltf/blob/962fed80d16bf71830034d0150cffdf85765fec6/src/playcanvas-gltf.js#L186-L198

But never cloned:

https://github.com/playcanvas/playcanvas-gltf/blob/962fed80d16bf71830034d0150cffdf85765fec6/src/playcanvas-anim.js#L37-L43

So cloned models with cubicspline curves currently don't work.

If I see it right, there are currently six kinds of `AnimationKeyable`'s:

* AnimationKeyableNum
* AnimationKeyableVec
* AnimationKeyableQuat
* AnimationKeyableNumCubicspline
* AnimationKeyableVecCubicspline
* AnimationKeyableQuatCubicspline

Would it be a good design choice to make six explicit standalone classes?

I currently have three arguments for it:

**Memory consumption**

Every model (has) clips (has) curves (has) keyables... so keyables are like one of the most allocated objects. Hence the memory consumption of each one should be as low as possible. E.g. there is no need to save `this.type` when the class/object itself represents it.

**Performance**

It will remove like a dozen of runtime checks like:

* `keyable.type === AnimationKeyableType.VEC`
* `if (this.value instanceof pc.Vec3 || this.value instanceof pc.Quat)`
* `switch (keyable.type) { ... }`

Ability to just call the methods and they know what to do.

**Type safety**

Dedicated classes make it harder to introduce bugs, because they don't need to work for five other use cases.

(TLDR: small, fast and type safe)

Probably @thomasbiang knows most about it.

**Comment by thomasbiang** [comment]
I'll try to make a separate class version, without breaking the current APIs.

**Comment by kungfooman** [comment]
That would be nice, I did the same here: https://github.com/KILLTUBE/playcanvas-gltf/blob/master/src/AnimationKeyable.js

And a bit code here: https://github.com/KILLTUBE/playcanvas-gltf/blob/master/src/playcanvas-anim.js

Basically `new AnimationKeyable` can be simply replaced by `new_AnimationKeyable`.

Feel free to reuse the code. "I confirm I have signed the Contributor License Agreement."

**Comment by thomasbiang** [comment]
The clone part is in the pull request https://github.com/playcanvas/playcanvas-gltf/pull/72
