### ISSUE TITLE
Hello, I'd like to ask which JSDoc template you use?

### ISSUE THREAD

**Issue by gameatp** [playcanvas/playcanvas-gltf#65]
Hello, I'd like to ask which JSDoc template you use.

**Comment by kungfooman** [comment]
Hi @gameatp, sorry, what do you mean with JSDoc template?

You can just open the repo in e.g. Visual Studio Code now and it will figure out all types for Intellisense/Autocomplete via the TypeScript language server.

**Comment by gameatp** [comment]
You didn't use a template like this.

Https://github.com/clenemt/docdash

To generate documents?

**Comment by kungfooman** [comment]
Oh, you speak about automatic documentation generation. I never did that yet, personally I just need JSDoc for code editing / understanding.

**Comment by gameatp** [comment]
> Oh, you speak about automatic documentation generation. I never did that yet, personally I just need JSDoc for code editing / understanding.

Okay, thank you. I thought this comment was written to generate the document.
