### ISSUE TITLE
new `pc.Vec3`/`pc.Quat` in `AnimationCurve.prototype.evalCUBICSPLINE_GLTF_cache`

### ISSUE THREAD

**Issue by kungfooman** [playcanvas/playcanvas-gltf#67]
Since every `AnimationKeyable` allocates its own `value` via constructor (in `init` method), it should always be initialized and `new pc.Vec3()`/`new pc.Quat()` can be removed. I don't see any special cases where an `AnimationKeyable` could be uninitialized.

https://github.com/playcanvas/playcanvas-gltf/blob/cabbeb18928ada8a28c785bfecf1965b252a68db/src/playcanvas-anim.js#L1195-L1205

https://github.com/playcanvas/playcanvas-gltf/blob/cabbeb18928ada8a28c785bfecf1965b252a68db/src/playcanvas-anim.js#L21-L41

**Comment by kungfooman** [comment]
Same idea here:

![image](https://user-images.githubusercontent.com/5236548/53925211-69b4ed80-407f-11e9-99ee-2e8cb2b3ca5d.png)

I just made a test with 64 models and VM memory usage dropped from 900mb to 600mb.

**Comment by thomasbiang** [comment]
Thank you. I'll update this soon.

**Comment by thomasbiang** [comment]
This is in the pull request as well https://github.com/playcanvas/playcanvas-gltf/pull/72.
