### ISSUE TITLE
Replace curve names (strings) with IDs (numbers)

### ISSUE THREAD

**Issue by kungfooman** [playcanvas/playcanvas-gltf#68]
I figured that curves names are mostly pretty pointless (e.g. `"curve" + id`), so I wondered if a can just completely replace them with IDs to reduce memory and optimize performance. And it works surprisingly well: https://github.com/KILLTUBE/playcanvas-gltf/commit/99f1c484e04ef134033f5ec38e7ed04eb088d05d

Instead of the `AnimationCurve.count++` I simply do `curve.name = this.animCurves.length;` inside `AnimationClip#addCurve`.

I tested some models and some clip blending and it all still works.

I don't know yet if I will run into problems later on, so I will just leave this issue here so everybody could sleep over it.

**Comment by thomasbiang** [comment]
Thank you for pointing out. One case it is used is for matching curve names with bone(joint) names in another project. I'll see how to get rid of the string.

**Comment by willeastcott** [comment]
Closing this PR since this repo is now retired in favor of the glTF parser in the core engine repo.
