### ISSUE TITLE
AnimationKeyable - normalize() is not a function

### ISSUE THREAD

**Issue by sakidev** [playcanvas/playcanvas-gltf#74]
So I wanted to test the glTF viewer with a simple mesh with simple animation and it just doesn't work.

![image](https://user-images.githubusercontent.com/49696473/59641440-d7ce7d80-9161-11e9-8b0e-0fd505bf8100.png)

The issue is here:

![image](https://user-images.githubusercontent.com/49696473/59641555-53302f00-9162-11e9-8131-803cbeb695f2.png)

It calls "normalize" when the resKey (which is an AnimationKeyable), doesn't contain a normalize function.

**Comment by willeastcott** [comment]
Can you share the mesh that causes this?

**Comment by sakidev** [comment]
Sure, I'm attaching it. Could you share an animated mesh which is working for you?


[character_base_idle.zip](https://github.com/playcanvas/playcanvas-gltf/files/3303955/character_base_idle.zip)

**Comment by willeastcott** [comment]
Fixed in 6eac172477085bd8f32e936be9d4239ace58bd4e
