### ISSUE TITLE
Error loading Draco model with latest version of glTF Loader

### ISSUE THREAD

**Issue by cx20** [playcanvas/playcanvas-gltf#75]
I tried to read Draco format files with the latest version of glTF Loader.
However, an error is output on the console and the model is not displayed.

[PlayCanvas v1.22.0dev + glTF Loader + Draco format model result:](https://rawcdn.githack.com/cx20/gltf-test/50e65c93d18cf51204f6241eec471df4f3a57857/examples/playcanvas/index.html?category=sampleModels&model=Duck&scale=1&type=glTF-Draco)

```
playcanvas-gltf.js:671 Uncaught TypeError: Cannot read property 'DecoderBuffer' of null
    at playcanvas-gltf.js:671
    at Array.forEach (<anonymous>)
    at translateMesh (playcanvas-gltf.js:644)
    at playcanvas-gltf.js:1274
    at Array.map (<anonymous>)
    at parse (playcanvas-gltf.js:1273)
    at playcanvas-gltf.js:1412
    at Image.onLoad (playcanvas-gltf.js:276)
```

I think the following fixes are affecting. The reason is that old code can load Draco format models correctly.
https://github.com/playcanvas/playcanvas-gltf/commit/e945af5fd4ed3c4945cc57e4847c3feb5316c5f0#diff-d6638a7dc049e197f0b086bececddae0

**Comment by willeastcott** [comment]
Thanks for reporting! 😄

**Comment by cx20** [comment]
I confirmed that it has been fixed in the latest version of glTF Loader. Thanks!
[Latest glTF Loader + Draco format model result:](https://rawcdn.githack.com/cx20/gltf-test/5869dcd47da9fcc6aa700d78069c4a85340963b6/examples/playcanvas/index.html?category=sampleModels&model=Duck&scale=1&type=glTF-Draco)
![image](https://user-images.githubusercontent.com/1833979/60342897-abcabc00-99ed-11e9-9e36-fd69bc1d0665.png)
