### ISSUE TITLE
A simple gltf cube render incorrectly in playcanvas gltf viewer, but it works in other engine

### ISSUE THREAD

**Issue by scarletsky** [playcanvas/playcanvas-gltf#76]
## Description

This cube is generated by our internal tools, and it can works in other gltf viewers except playcanvas gltf viewer.

[cube.zip](https://github.com/playcanvas/playcanvas-gltf/files/3341954/cube.zip)

The `cube.zip` includes two files: `cube.gltf` and `cube.bin`.

In playcanvas gltf viewer:

![image](https://user-images.githubusercontent.com/2386165/60385370-14cc3580-9abb-11e9-8091-d77ad211744b.png)

In other engine(in vscode gltf viewer):

- Babylon.js

![image](https://user-images.githubusercontent.com/2386165/60385383-33323100-9abb-11e9-8a36-77ced4745a8e.png)

- Cesium

![image](https://user-images.githubusercontent.com/2386165/60385403-5e1c8500-9abb-11e9-90e8-adab1bf1f1b6.png)

- Three.js

![image](https://user-images.githubusercontent.com/2386165/60385432-96bc5e80-9abb-11e9-88bc-9be1015518af.png)

**Comment by willeastcott** [comment]
This is because your vertex data is interleaved. The loader doesn't yet support interleaved vertex data. So this is actually a duplicate issue of #7.

**Comment by scarletsky** [comment]
Oh, sorry for the duplicate issue. 😄
