### ISSUE TITLE
KHR_materials_unlit not correctly handled

### ISSUE THREAD

**Issue by aidinabedi** [playcanvas/playcanvas-gltf#77]
### Description

The unlit material extension `KHR_materials_unlit` is not correctly handled in PlayCanvas glTF loader. Lighting calculations are still somewhat being applied to an un-lit material. For more information on how it should look, please see: [KhronosGroup/glTF-Sample-Models/2.0/UnlitTest](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/UnlitTest)

### Steps to Reproduce

1. Download model: [KhronosGroup/glTF-Sample-Models/2.0/UnlitTest/glTF-Binary/UnlitTest.glb](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/UnlitTest/glTF-Binary/UnlitTest.glb?raw=true)
2. Go to PlayCanvas viewer: https://playcanvas.github.io/playcanvas-gltf/viewer/
3. Drag and drop model `UnlitTest.glb` into PlayCanvas viewer.

### What I expected to see

![khronosgroup-gltf-sample-unlittest](https://user-images.githubusercontent.com/255073/61253595-ce850080-a761-11e9-89da-48704e064eff.jpg)

### What I see instead

![playcanvas-gltf-viewer-unlittest](https://user-images.githubusercontent.com/255073/61253605-d80e6880-a761-11e9-9da6-50fe398e2841.jpg)

**Comment by willeastcott** [comment]
Closing since glTF support is now available in the core engine. `KHR_materials_unlit` is supported there.
