### ISSUE TITLE
Point cloud not rendered

### ISSUE THREAD

**Issue by aidinabedi** [playcanvas/playcanvas-gltf#79]
### Description

Primitives of type `POINTS` are not displayed. 

### Steps to Reproduce

1. Download and unzip model: [mickey_mouse_test_color_point_cloud.glb.zip](https://github.com/playcanvas/playcanvas-gltf/files/3394527/mickey_mouse_test_color_point_cloud.glb.zip)
2. Go to PlayCanvas viewer: https://playcanvas.github.io/playcanvas-gltf/viewer/
3. Drag and drop model `mickey_mouse_test_color_point_cloud.glb` into PlayCanvas viewer.

### What I expected to see

![babylonjs-gltf-pointtest](https://user-images.githubusercontent.com/255073/61254807-3d645880-a766-11e9-9181-233ef6f62cc5.png)

### What I see instead

![playcanvas-gltf-pointtest](https://user-images.githubusercontent.com/255073/61254812-43f2d000-a766-11e9-88d1-64c6d7107ed9.png)

**Comment by willeastcott** [comment]
It looks like this is actually a bug in the core engine. The engine probably doesn't currently correctly support [pc.PRIMITIVE_POINTS](https://developer.playcanvas.com/en/api/pc.html#PRIMITIVE_POINTS). And there's definitely no API to support point size. I'm going to open an issue on this against the engine repo.

**Comment by aidinabedi** [comment]
To be fair, I don't think there is a nice way to implement point size in the engine IMHO ([see my comment](https://github.com/playcanvas/engine/issues/1621#issuecomment-511704590)). I don't see much point in it ;)

**Comment by mvaligursky** [comment]
just an update - I tried current version of PlayCanvas and it loads and renders the model. The only issue I see is that the camera does not look at the model when loaded, so you need to look around to find it. I'll see what that is. But point cloud (at least without point size API) works.

**Comment by willeastcott** [comment]
Haha, amazing. Looks like I was wrong then. 🤣
