### ISSUE TITLE
FlightHelmet.gltf goggles are opacity

### ISSUE THREAD

**Issue by cx20** [playcanvas/playcanvas-gltf#8]
I tried to display a new sample model [FlightHelmet.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/FlightHelmet) with the library of the latest version of playcanvas-gltf.
However, in PlayCanvas, the appearance of goggles seems to be different from other libraries.

|Three.js|Babylon.js|PlayCanvas|
|:-------:|:-----------:|:------:|
|[![image](https://user-images.githubusercontent.com/1833979/37533089-41ba14da-2984-11e8-95a7-bc4b5e3b4eae.png)](https://cx20.github.io/gltf-test/examples/threejs/index.html?category=tutorialModels&model=FlightHelmet&scale=0.5&type=glTF)|[![image](https://user-images.githubusercontent.com/1833979/37533098-49ee0238-2984-11e8-9ff1-5f7d00ef32b6.png)](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?category=tutorialModels&model=FlightHelmet&scale=0.5&type=glTF)|[![image](https://user-images.githubusercontent.com/1833979/37523185-7e5a7f4e-2969-11e8-8038-6c52a23c62a5.png)](https://cx20.github.io/gltf-test/examples/playcanvas/index.html?category=tutorialModels&model=FlightHelmet&scale=0.5&type=glTF)|

**Comment by willeastcott** [comment]
Fixed in https://github.com/playcanvas/playcanvas-gltf/commit/6505647de77273aa0b9e368ef058e5651a8173e0

![image](https://user-images.githubusercontent.com/697563/37557960-a39fc088-29c9-11e8-8a36-b23f69952825.png)

**Comment by cx20** [comment]
I confirmed that FlightHelmet.gltf is displayed correctly.

|Three.js|PlayCanvas|
|:-------:|:-------:|
|![image](https://user-images.githubusercontent.com/1833979/37548605-7ca5241c-29bc-11e8-8a1e-cc20a9718b57.png)|![image](https://user-images.githubusercontent.com/1833979/37560384-2e3595e6-2a7a-11e8-995f-bf74968f54cb.png)|
