### ISSUE TITLE
Hardcoded path to playcanvas.github.io

### ISSUE THREAD

**Issue by kungfooman** [playcanvas/playcanvas-gltf#82]
Was this supposed in last commit?

https://github.com/playcanvas/playcanvas-gltf/blob/73fecd830c3377328226ea4bb7ada61c2537992d/viewer/index.html#L10-L11

**Comment by willeastcott** [comment]
I did that to fix the Electron build because before, those files were referenced outside of the viewer subfolder, which electron-packager doesn't like. If you can think of an alternative solution, I'd be very interested! 😄
