### ISSUE TITLE
Plans for supporting glTF export?

### ISSUE THREAD

**Issue by aidinabedi** [playcanvas/playcanvas-gltf#86]
We are in need of a way to serialize or save a PlayCanvas scene or at-least part of a scene to glTF format. In our case, our 3D configurator procedurally builds a scene (ex a vehicle, room or instrument) based on 100-1000+ rules and we want to, for example, allow the user to download the scene as a `.glb` file and open it in a glTF-supporting AR-capable 3D viewer app on their phone. This is just one of multiple use-cases for us.

Both [Babylon.js](https://doc.babylonjs.com/extensions/gltfexporter) and [three.js](https://threejs.org/docs/#examples/en/exporters/GLTFExporter) support this. Are there any plans on adding support for this in PlayCanvas?

**Comment by willeastcott** [comment]
I've just checked in a super-preliminary sketch of a GLB exporter:

https://github.com/playcanvas/playcanvas-gltf/blob/master/src/export-gltf.js

Right now, it just generates a download of a GLB containing the entity hierarchy. Ignores meshes, animations, lights and cameras for now. But it's a starting point! Checking something in just in case anybody else wants to contribute. 😄

**Comment by aidinabedi** [comment]
Thank you @willeastcott. I'll take stab at it, hopefully, next month after some critical deadlines.

**Comment by willeastcott** [comment]
Not yet @ThorstenBux (at least, not from me). I'm not sure if @aidinabedi looked into this at all. Just so you know, we're making really awesome progress fully 100% integrating glTF (GLB specifically) into the Editor itself. While it doesn't have glTF export in the initial release, it would be a cool feature to add (e.g. right click any entity in the hierarchy and say 'Export GLB'). cc @slimbuck

**Comment by aidinabedi** [comment]
Hello @ThorstenBux. We've actually started working on a glTF exporter. However, it's written entirely in TypeScript (to reduce development time) and I'm not sure how to contribute it back to this repo. I'm open to suggestions, @willeastcott?

**Comment by willeastcott** [comment]
So here's the thing @aidinabedi. This repo will probably be deprecated soon because the main engine repo is [about to receive](https://github.com/playcanvas/engine/pull/1904) first class support for loading GLB files. However, the engine won't (at least initially) have support for _exporting_ glTF. So I'm wondering if this might warrant a new repo (called playcanvas-gltf-exporter or something). 😄

**Comment by kungfooman** [comment]
@aidinabedi Do you share the source of the exporter somewhere? I converted lots of playcanvas-gltf code to TypeScript aswell, to make it easier to read, debug and composable with other TS projects. https://github.com/KILLTUBE/playcanvas-gltf

Currently working on another project, but once I come back to 3D programming, I would enjoy synthesizing all features together through TS.

**Comment by silvainSayduck** [comment]
Hi! 

I am also trying to export a scene at runtime, and I was wondering what was the status on this?

My use case is to get glTF files (or if not possible some other 3D format) from some old PlayCanvas JSON assets for which I unfortunately do not have the original models anymore. As far as I understand, loading these JSON files is currently only doable at runtime, and as such, a runtime exporter would also be needed...

I have taken a look at the very initial `export-gltf.js` file, but I do not understand how I could build on it, as I am not sure the underlying 3D data that would need to be packaged is actually accessible? @aidinabedi would you be able to share some insight and/or code?

Thanks a lot in advance!

**Comment by kungfooman** [comment]
> I am also trying to export a scene at runtime, and I was wondering what was the status on this?

Current status is that this repo is somewhat obsolete and the active development of glTF is in the engine itself now.

I'm happy that @willeastcott is continuing the work on the exporter here: https://github.com/playcanvas/engine/pull/3366/

**Comment by willeastcott** [comment]
Yeah, as a result, I'll close this issue since the work is continuing in the main repo.
