### ISSUE TITLE
feature request about animation playback

### ISSUE THREAD

**Issue by velbi** [playcanvas/playcanvas-gltf#94]
It would be great if there was a reverse play function in playcanvas-anim.js

**Comment by willeastcott** [comment]
Hey @thomasbiang - does the animation system you wrote support negative time steps?

**Comment by kungfooman** [comment]
A `playReverse()` method could use:

```js
viewer.animationClips[0].bySpeed = -1
```

**Comment by velbi** [comment]
It's work! thank you @willeastcott  and @kungfooman
