### ISSUE TITLE
Pictures that are not a power of 2 cannot be displayed

### ISSUE THREAD

**Issue by wei292224644** [playcanvas/playcanvas-gltf#97]
https://github.com/playcanvas/playcanvas-gltf/blob/72329941357d51399324adcfbfb828ae7c826715/src/playcanvas-gltf.js#L291

i think the problem is here.

**Comment by wei292224644** [comment]
The width of this texture is a power of 2,but height is not

**Comment by willeastcott** [comment]
Thanks for reporting this! I have fixed it.
